### ISSUE TITLE
Agregar video de presentacion grupal por integrante

### ISSUE THREAD

**Issue by Maxg8704** [ISPC-TST-ELECTRONICA-MICROCONTROLADA/proyecto-1-grupo-02#13]

**Comment by NahuelDe** [comment]
https://user-images.githubusercontent.com/63590294/233874438-8f90c18e-1ec6-47fd-879b-be8e6eb5b119.mp4

**Comment by Maxg8704** [comment]
Link Video de Presentacion de Proyecto Grupal: 

https://drive.google.com/file/d/1IqIs-283KVwTXiYG-mrrgTA1uq1RlDIF/view
